input          : "/<full path to Sanibel>/fastqs"
output    : "/<full path to Sanibel>/output"

# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

