# Input / Output absolute path, no trailing slash "/"
input:  "/full/path/to/fastqs"
output: "/full/path/to/output"


# non-HiPerGator users: set this to your BMGAP2 analysis_scripts directory
bmgap2_db:  "/blue/bphl-florida/share/bmgap2"
