input          : "/blue/bphl-florida/dongyibo/Dev_Sanibel_072023/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_Sanibel_072023/output"

# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

