input          : "/blue/bphl-florida/dongyibo/Dev_module_Sanibel/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_module_Sanibel/output"

# Note: The parameter "input" and "output" are the absolute path. Do not include the "/" at the end of the paths.

